#!/bin/bash

# Array of repository URLs
repos=(
    "https://github.com/ros/rosdistro"
    "https://github.com/cloudfoundry/cloud_controller_ng"
    "https://github.com/edx/configuration"
    "https://github.com/matplotlib/matplotlib"
    "https://github.com/ansible/ansible-modules-extras"
    "https://github.com/DataDog/dd-agent"
    "https://github.com/ansible/ansible-modules-core"
    "https://github.com/rg3/youtube-dl"
    "https://github.com/Theano/Theano"
    "https://github.com/emberjs/guides"
    "https://github.com/zulip/zulip"
    "https://github.com/bbatsov/rubocop"
    "https://github.com/bundler/bundler"
    "https://github.com/coreos/rkt"
    "https://github.com/google/closure-compiler"
    "https://github.com/Kapeli/Dash-User-Contributions"
    "https://github.com/Katello/katello"
    "https://github.com/samtools/htsjdk"
    "https://github.com/zendesk/samson"
    "https://github.com/thoughtbot/suspenders"
    "https://github.com/sferik/rails_admin"
    "https://github.com/scikit-image/scikit-image"
    "https://github.com/Flexget/Flexget"
    "https://github.com/GeoNode/geonode"
    "https://github.com/biolab/orange3"
    "https://github.com/oppia/oppia"
    "https://github.com/svenfuchs/rails-i18n"
    "https://github.com/rubygems/rubygems"
    "https://github.com/spotify/luigi"
    "https://github.com/docker/machine"
    "https://github.com/hylang/hy"
    "https://github.com/apache/libcloud"
    "https://github.com/refinery/refinerycms"
    "https://github.com/DSpace/DSpace"
    "https://github.com/elastic/logstash"
    "https://github.com/pyca/cryptography"
    "https://github.com/KeepSafe/aiohttp"
    "https://github.com/lisa-lab/pylearn2"
    "https://github.com/python/mypy"
    "https://github.com/thoughtbot/shoulda-matchers"
    "https://github.com/gratipay/gratipay.com"
    "https://github.com/pypa/pip"
    "https://github.com/twisted/twisted"
    "https://github.com/plataformatec/simple_form"
    "https://github.com/cloudfoundry/loggregator"
    "https://github.com/fastlane/fastlane"
    "https://github.com/travis-ci/travis-build"
    "https://github.com/pfnet/chainer"
    "https://github.com/Yelp/paasta"
    "https://github.com/stephenmcd/mezzanine"
)

# Loop through the repository URLs and clone each one
for repo in "${repos[@]}"; do
    git clone "$repo"
done